---
title: "TITLE"
author: David Barnett
date: last-modified
format: html
keep-md: false
theme: 
  light: flatly
  dark: darkly
embed-resources: true
code-block-border-left: true
code-block-bg: true
toc: true
toc-location: right
toc-depth: 4
toc-expand: 3
number-sections: true
number-depth: 3
fig-align: center
fig-dpi: 300
fig-width: 7.5
fig-height: 5
fig-responsive: true
code-tools: true
code-fold: true
code-link: false
lightbox: auto
cache: false
---

```{r}
# load packages, do you need data packages?
library(tidyverse) # do you really need the whole tidyverse?
library(here)
library(phyloseq)
library(microViz)
```

## Intro

aims and preamble

## Get data

```{r}

```

## Analysis

```{r}

```

## More Info

-   Created following instructions here:\
    <https://quarto.org/docs/extensions/starter-templates.html>
-   Learn more about controlling the appearance of HTML output here:\
    <https://quarto.org/docs/output-formats/html-basics.html>

## Session info

<details>

```{r}
sessioninfo::session_info()
```

</details>
